site_name: On-Demend
site_url: https://on-demend.github.io/502_Bad_Gateway/
site_description: 502 Bad Gateway
site_author: On-Demand
repo_url: https://github.com/On-Demend/502_Bad_Gateway
repo_name: On-Demend/502_Bad_Gateway
edit_uri: edit/main/docs/
language: ko
nav:
  - "Home": index.md
  - "Getting Started":
    - "Linux":
      - "What is Linux": "tutorial/linux/what-is-linux.md"
      - "Commands": "tutorial/linux/commands.md"
      - "Exam 1": "tutorial/linux/exam.md"
      - "Exam 2": "tutorial/linux/exam2.md"
    - "Network":
      - "IP & Subnet": "tutorial/Network/IP.md"
      - "Protocols": "tutorial/Network/Protocols.md"
      - "HTTP": "tutorial/Network/HTTP.md"
theme:
  name: bootstrap386
  logo: "logos/on-demend.png"
  favicon: "logos/on-demend.png"
  icon:
    repo: fontawesome/brands/github